services:
  smartlegal_mysql:
    image: mysql:8.0
    container_name: smartlegal_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartlegal
    command: >
      --default-authentication-plugin=mysql_native_password
      --skip_ssl
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
