version: "3.9"

services:
  smartlegal_mysql:
    image: mysql:8.0
    container_name: smartlegal_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartlegal
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
